services:
  server:
    build: .
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - $SERVER_PORT:$SERVER_PORT

  postgres:
    command: ["postgres", "-c", "log_statement=all"]
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_URL"]
      interval: 10s
      timeout: 5s
      retries: 10
    image: postgres:alpine

  redis:
    env_file: .env
    image: redis/redis-stack-server
